version: '3'

services:

  prometheus:
   image: prom/prometheus:latest
   container_name: prometheus
   hostname: prometheus
   volumes:
      - ./prometheus:/etc/prometheus/
   command:
      - --config.file=/etc/prometheus/prometheus.yml
   ports:
      - 9090:9090
   restart: unless-stopped
   depends_on:
     - node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: node-exporter
    hostname: node-exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    hostname: grafana 
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning
    restart: unless-stopped
    depends_on:
      - prometheus
